export const ADD_PRODUCT = "http://localhost:8084/product/add"
export const GET_ALL_PRODUCTS = "http://localhost:8084/product/getallproducts"
export const GET_BY_PRODUCT = "http://localhost:8084/product/getby/"
export const DELETE_PRODUCT = "http://localhost:8084/product/delete/"
export const GET_BY_ID = "http://localhost:8084/product/getbyid/"
export const UPDATE_PRODUCT = "http://localhost:8084/product/update/"